/**
 * storyApi.ts — resolving which story the viewer should render, and fetching it.
 *
 * Three sources, in priority order:
 *   ?s=<id>    a published story, fetched from the story host
 *   ?draft=1   the studio's local draft, read from localStorage (same device
 *              only — this is the studio's preview path, not a share link)
 *   neither    the bundled default story
 *
 * Every failure degrades to the bundled default rather than throwing: a bad id,
 * an offline device, a malformed document, or a disabled host must never leave
 * a visitor staring at a broken experience.
 *
 * Source resolution is pure string logic so it is unit-testable without a DOM.
 */

/** localStorage key the studio writes its working draft to. */
export const LOCAL_DRAFT_KEY = 'arcade.studio.draft';

/**
 * Base URL stories are published under. Empty disables remote loading, matching
 * how API_BASE_URL gates the poster-asset path.
 */
const STORY_BASE_URL: string = import.meta.env.VITE_STORY_BASE_URL || '';

/** Where the viewer should get its story from. */
export type StorySource =
  | { kind: 'published'; id: string }
  | { kind: 'draft' }
  | { kind: 'default' };

/** Ids are generated by publish; keep the accepted shape narrow. */
const ID_PATTERN = /^[a-z0-9][a-z0-9-]{0,63}$/;

/**
 * Decides which story to load from a URL query string.
 *
 * @param search — `location.search`, with or without the leading '?'.
 * @returns The resolved source. Unrecognised or malformed ids fall to 'default'.
 */
export function resolveStorySource(search: string): StorySource {
  const params = new URLSearchParams(search.startsWith('?') ? search.slice(1) : search);

  const id = params.get('s');
  if (id !== null) {
    const trimmed = id.trim().toLowerCase();
    // A malformed id is a typo or a probe, not a reason to show nothing.
    return ID_PATTERN.test(trimmed) ? { kind: 'published', id: trimmed } : { kind: 'default' };
  }

  if (params.get('draft') === '1') return { kind: 'draft' };

  return { kind: 'default' };
}

/** True when a story host is configured. */
export function isStoryHostConfigured(): boolean {
  return STORY_BASE_URL !== '';
}

/**
 * Builds the public URL for a published story document.
 *
 * @param id — Story id, already validated by resolveStorySource.
 * @returns The absolute document URL.
 */
export function publishedStoryUrl(id: string): string {
  return `${STORY_BASE_URL.replace(/\/$/, '')}/stories/${encodeURIComponent(id)}.json`;
}

/**
 * Fetches a published story document.
 *
 * @param id — Story id.
 * @returns The parsed document, or null on any failure (unconfigured host,
 *   network error, non-2xx, unparseable body). Never throws.
 */
export async function fetchPublishedStory(id: string): Promise<unknown | null> {
  if (!isStoryHostConfigured()) return null;
  try {
    const res = await fetch(publishedStoryUrl(id), { credentials: 'omit' });
    if (!res.ok) return null;
    return (await res.json()) as unknown;
  } catch {
    return null;
  }
}

/**
 * Reads the studio's local draft.
 *
 * @returns The parsed draft, or null when absent or unparseable. Never throws.
 */
export function readLocalDraft(): unknown | null {
  try {
    const raw = window.localStorage.getItem(LOCAL_DRAFT_KEY);
    return raw === null ? null : (JSON.parse(raw) as unknown);
  } catch {
    return null;
  }
}

/**
 * Loads whichever story the current URL asks for.
 *
 * @param search — `location.search`.
 * @returns The raw document to hand to contentStore.load(), or null to keep the
 *   bundled default.
 */
export async function loadStoryForLocation(search: string): Promise<unknown | null> {
  const source = resolveStorySource(search);
  if (source.kind === 'published') return fetchPublishedStory(source.id);
  if (source.kind === 'draft') return readLocalDraft();
  return null;
}
