/**
 * storyApi.ts — resolving which story the viewer should render, and fetching it.
 *
 * Three sources, in priority order:
 *   ?s=<id>    a published story, fetched from the story host
 *   ?draft=1   the studio's local draft, read from localStorage (same device
 *              only — this is the studio's preview path, not a share link)
 *   neither    the bundled default story
 *
 * Every failure degrades to the bundled default rather than throwing: a bad id,
 * an offline device, a malformed document, or a disabled host must never leave
 * a visitor staring at a broken experience.
 *
 * Source resolution is pure string logic so it is unit-testable without a DOM.
 */

import { hydrateArt } from '@/story/artTokens';
import { resolveAssets } from '@/story/assetResolver';
import type { StoryDoc } from '@/story/storyDoc';

/** localStorage key the studio writes its working draft to. */
export const LOCAL_DRAFT_KEY = 'arcade.studio.draft';

/**
 * Base URL stories are published under. Empty disables remote loading, matching
 * how API_BASE_URL gates the poster-asset path.
 */
const STORY_BASE_URL: string = import.meta.env.VITE_STORY_BASE_URL || '';

/** Where the viewer should get its story from. */
export type StorySource =
  | { kind: 'published'; id: string }
  | { kind: 'draft' }
  | { kind: 'default' };

/** Ids are generated by publish; keep the accepted shape narrow. */
const ID_PATTERN = /^[a-z0-9][a-z0-9-]{0,63}$/;

/**
 * Decides which story to load from a URL query string.
 *
 * @param search — `location.search`, with or without the leading '?'.
 * @returns The resolved source. Unrecognised or malformed ids fall to 'default'.
 */
export function resolveStorySource(search: string): StorySource {
  const params = new URLSearchParams(search.startsWith('?') ? search.slice(1) : search);

  const id = params.get('s');
  if (id !== null) {
    const trimmed = id.trim().toLowerCase();
    // A malformed id is a typo or a probe, not a reason to show nothing.
    return ID_PATTERN.test(trimmed) ? { kind: 'published', id: trimmed } : { kind: 'default' };
  }

  if (params.get('draft') === '1') return { kind: 'draft' };

  return { kind: 'default' };
}

/** True when a story host is configured. */
export function isStoryHostConfigured(): boolean {
  return STORY_BASE_URL !== '';
}

/**
 * Builds the public URL for a published story document.
 *
 * @param id — Story id, already validated by resolveStorySource.
 * @returns The absolute document URL.
 */
export function publishedStoryUrl(id: string): string {
  return `${STORY_BASE_URL.replace(/\/$/, '')}/stories/${encodeURIComponent(id)}.json`;
}

/**
 * Fetches a published story document.
 *
 * @param id — Story id.
 * @returns The parsed document, or null on any failure (unconfigured host,
 *   network error, non-2xx, unparseable body). Never throws.
 */
export async function fetchPublishedStory(id: string): Promise<unknown | null> {
  if (!isStoryHostConfigured()) return null;
  try {
    const res = await fetch(publishedStoryUrl(id), { credentials: 'omit' });
    if (!res.ok) return null;
    return (await res.json()) as unknown;
  } catch {
    return null;
  }
}

/**
 * Reads the studio's local draft.
 *
 * @returns The parsed draft, or null when absent or unparseable. Never throws.
 */
export function readLocalDraft(): unknown | null {
  try {
    const raw = window.localStorage.getItem(LOCAL_DRAFT_KEY);
    return raw === null ? null : (JSON.parse(raw) as unknown);
  } catch {
    return null;
  }
}

/** Outcome of a publish attempt. Never throws; failures are values. */
export type PublishOutcome =
  | { ok: true; id: string; url: string; viewUrl: string }
  | { ok: false; error: string };

/**
 * Turns a title into a publishable id.
 *
 * @param title — The story title.
 * @returns A slug matching the id pattern the publish endpoint accepts.
 */
export function slugifyStoryId(title: string): string {
  const slug = title
    .toLowerCase()
    .replace(/[^a-z0-9]+/g, '-')
    .replace(/^-+|-+$/g, '')
    .slice(0, 48);
  // The endpoint requires a leading alphanumeric and a non-empty value.
  return /^[a-z0-9]/.test(slug) ? slug : `story-${slug}`.replace(/-+$/, '') || 'story';
}

/** What distinguishes one publishable kind from another. */
interface PublishTarget {
  /** The API route. */
  endpoint: string;
  /** Query parameter a visitor link carries — `s` for a story, `e` for an exhibit. */
  param: string;
  /** Noun used when the server accepts the write but names no location. */
  noun: string;
}

/**
 * Posts a document to a publish endpoint.
 *
 * Stories and exhibits publish through the same shape — bearer secret in the
 * header and never in the body, server error text preferred over a generic
 * status message, every failure returned as a value rather than thrown — so
 * the shape lives here once. Only the route, the link's query parameter, and
 * one noun differ, which is what `PublishTarget` carries. Extracted for the
 * same reason `contentUpload.ts` was pulled out of `assetApi.ts`: a second
 * copy is a second place for the auth handling to drift.
 *
 * @param target — Which kind of document is being published.
 * @param doc — The document.
 * @param id — Its id; becomes the visitor link's query value.
 * @param secret — The publish secret, sent as a bearer token.
 * @returns The published location, or a message explaining why it failed.
 */
async function publishDocument(
  target: PublishTarget,
  doc: unknown,
  id: string,
  secret: string,
): Promise<PublishOutcome> {
  try {
    const res = await fetch(target.endpoint, {
      method: 'POST',
      headers: {
        'content-type': 'application/json',
        authorization: `Bearer ${secret}`,
      },
      body: JSON.stringify({ id, doc }),
    });

    const payload = (await res.json().catch(() => ({}))) as { url?: string; error?: string };
    if (!res.ok) {
      return { ok: false, error: payload.error ?? `Publish failed (${res.status}).` };
    }
    if (typeof payload.url !== 'string') {
      return { ok: false, error: `The server did not return ${target.noun}.` };
    }
    return {
      ok: true,
      id,
      url: payload.url,
      viewUrl: `${window.location.origin}/?${target.param}=${encodeURIComponent(id)}`,
    };
  } catch {
    return { ok: false, error: 'Could not reach the server. Check your connection.' };
  }
}

/**
 * Publishes a story document.
 *
 * @param doc — The document to publish.
 * @param id — Story id; becomes the `?s=` value.
 * @param secret — The publish secret, sent as a bearer token.
 * @returns The published location, or a message explaining why it failed.
 */
export async function publishStory(
  doc: unknown,
  id: string,
  secret: string,
): Promise<PublishOutcome> {
  return publishDocument(
    { endpoint: '/api/publish', param: 's', noun: 'a story location' },
    doc,
    id,
    secret,
  );
}

/**
 * Publishes an exhibit document.
 *
 * Note this posts the exhibit as submitted. The endpoint refuses an over-long
 * or duplicated story list rather than trimming it, so the caller should show
 * `exhibitIssues` before getting here — but the server is the authority, and
 * its 422 text is what reaches the operator on the paths the UI missed.
 *
 * @param doc — The exhibit to publish.
 * @param id — Exhibit id; becomes the `?e=` value.
 * @param secret — The publish secret, sent as a bearer token.
 * @returns The published location, or a message explaining why it failed.
 */
export async function publishExhibit(
  doc: unknown,
  id: string,
  secret: string,
): Promise<PublishOutcome> {
  return publishDocument(
    { endpoint: '/api/publish-exhibit', param: 'e', noun: 'an exhibit location' },
    doc,
    id,
    secret,
  );
}

/**
 * Loads whichever story the current URL asks for.
 *
 * @param search — `location.search`.
 * @returns The raw document to hand to contentStore.load(), or null to keep the
 *   bundled default.
 */
export async function loadStoryForLocation(search: string): Promise<unknown | null> {
  const source = resolveStorySource(search);
  if (source.kind === 'published') return fetchPublishedStory(source.id);
  if (source.kind === 'draft') return readLocalDraft();
  return null;
}

/**
 * Inlines every referenced asset into the document's art.
 *
 * Call once after loading and before anything rasterizes. The result is
 * render-only: its `art` strings carry full image payloads, so it must never
 * be written back to the draft, persisted, or published.
 *
 * @param doc — A validated document, freshly loaded.
 * @returns A copy whose frames' art is ready for `svgToTexture`. Documents
 *   with no assets — every hand-drawn era scene — are returned untouched.
 */
export async function hydrateStoryDoc(doc: StoryDoc): Promise<StoryDoc> {
  if (!doc.assets || Object.keys(doc.assets).length === 0) return doc;

  const resolved = await resolveAssets(doc.assets);
  return {
    ...doc,
    frames: doc.frames.map((f) => ({ ...f, art: hydrateArt(f.art, resolved) })),
  };
}
