/**
 * posterStore — Zustand store for poster state.
 *
 * Single source of truth for:
 *   - `posters`: the posters currently placed in the scene (capped at
 *     `maxPosters`, from VITE_MAX_POSTERS). The AR layer mirrors mutations
 *     here into the three.js scene via a store subscription (see
 *     ARExperience.tsx) — removing or rescaling a poster in the store updates
 *     the rendered mesh.
 *   - `uploadedPosters`: user-uploaded images available in the gallery.
 *   - `currentPosterImage`: the image the next placement will use.
 *
 * Note: `position`/`rotation`/`scale` on a placed poster mirror the values
 * passed at creation; the authoritative world transform of a placed poster is
 * the three.js group matrix owned by PosterPlacement, not this store.
 */

import { create } from 'zustand';
import { Poster, CreatePosterOptions } from '@/types';
import {
  DEFAULT_POSTER_DEPTH,
  DEFAULT_POSTER_HEIGHT,
  DEFAULT_POSTER_IMAGE,
  DEFAULT_POSTER_WIDTH,
  MAX_POSTERS,
} from '@/utils/constants';

/**
 * A user-uploaded poster image available in the gallery (not yet necessarily
 * placed in the scene).
 */
export interface UploadedPoster {
  /** Unique ID assigned by the store. */
  id: string;
  /** Data URL of the processed image (WebP, or the original GIF bytes). */
  imageUrl: string;
  /** Original filename, shown in the gallery. */
  name: string;
  /** Upload timestamp (Date.now()). */
  uploadedAt: number;
  /** Decoded image width in pixels. */
  width: number;
  /** Decoded image height in pixels. */
  height: number;
}

interface PosterStore {
  // State
  /** Posters currently placed in the scene (capped at `maxPosters`). */
  posters: Poster[];
  /** ID of the selected poster (most recently placed), or null. */
  selectedPosterId: string | null;
  /** Placement cap, from VITE_MAX_POSTERS. */
  maxPosters: number;
  /** User-uploaded images available in the gallery. */
  uploadedPosters: UploadedPoster[];
  /** Image (data URL or bundled path) the next placement will use. */
  currentPosterImage: string;

  // Actions
  /**
   * Appends a new poster to `posters` and selects it.
   *
   * @param options — Image URL plus optional position/rotation/scale;
   *   omitted transforms fall back to the defaults below.
   * @returns The new poster's ID, or null when the `maxPosters` cap is
   *   already reached (a console warning is logged; state is unchanged).
   */
  addPoster: (options: CreatePosterOptions) => string | null;
  /**
   * Removes a poster from `posters`; clears `selectedPosterId` if it pointed
   * at the removed poster.
   *
   * @param id — ID of the poster to remove; unknown IDs are a no-op.
   */
  removePoster: (id: string) => void;
  /**
   * Shallow-merges `updates` into the matching poster and bumps its
   * `updatedAt` timestamp.
   *
   * @param id — ID of the poster to update; unknown IDs are a no-op.
   * @param updates — Partial Poster fields to overwrite (e.g. `scale`).
   */
  updatePoster: (id: string, updates: Partial<Poster>) => void;
  /**
   * Sets `selectedPosterId`.
   *
   * @param id — Poster ID to select, or null to deselect.
   */
  selectPoster: (id: string | null) => void;
  /** Empties `posters` and clears the selection. Uploads are untouched. */
  clearPosters: () => void;
  /**
   * Looks up a placed poster. Does not change state.
   *
   * @param id — Poster ID to find.
   * @returns The poster, or undefined when no poster has that ID.
   */
  getPosterById: (id: string) => Poster | undefined;

  // Upload management
  /**
   * Appends an upload to `uploadedPosters` and makes it the
   * `currentPosterImage` so the next placement uses it.
   *
   * @param poster — Image URL, name, and pixel size; `id` and `uploadedAt`
   *   are generated by the store.
   * @returns The new upload's ID.
   */
  addUploadedPoster: (poster: Omit<UploadedPoster, 'id' | 'uploadedAt'>) => string;
  /**
   * Removes an upload from the gallery. If it was the active
   * `currentPosterImage`, falls back to the first remaining upload, or the
   * bundled default when none are left.
   *
   * @param id — ID of the upload to remove; unknown IDs are a no-op.
   */
  removeUploadedPoster: (id: string) => void;
  /**
   * Sets `currentPosterImage` directly (gallery selection).
   *
   * @param imageUrl — Image URL the next placement should use.
   */
  setCurrentPosterImage: (imageUrl: string) => void;
  /**
   * Merges server-persisted assets into the gallery on startup. Appends any
   * whose id is not already present; never changes currentPosterImage.
   *
   * @param assets — Remote assets returned by listAssets().
   */
  hydrateUploads: (assets: import('@/services/posterApi').RemoteAsset[]) => void;
}

/**
 * Generates a unique ID for a placed poster.
 *
 * @returns A string like `poster-<timestamp>-<random>`.
 */
const generatePosterId = (): string => {
  return `poster-${Date.now()}-${Math.random().toString(36).slice(2, 11)}`;
};

/**
 * Default poster configuration (dimensions come from utils/constants.ts).
 */
const DEFAULT_POSTER_SCALE: [number, number, number] = [
  DEFAULT_POSTER_WIDTH,
  DEFAULT_POSTER_HEIGHT,
  DEFAULT_POSTER_DEPTH,
];
const DEFAULT_POSTER_POSITION: [number, number, number] = [0, 1.5, -2];
const DEFAULT_POSTER_ROTATION: [number, number, number] = [0, 0, 0];

/**
 * Generates a unique ID for an uploaded gallery image.
 *
 * @returns A string like `uploaded-<timestamp>-<random>`.
 */
const generateUploadedPosterId = (): string => {
  return `uploaded-${Date.now()}-${Math.random().toString(36).slice(2, 11)}`;
};

/**
 * Poster store using Zustand
 */
export const usePosterStore = create<PosterStore>((set, get) => ({
  // Initial state
  posters: [],
  selectedPosterId: null,
  maxPosters: MAX_POSTERS,
  uploadedPosters: [],
  currentPosterImage: DEFAULT_POSTER_IMAGE,

  // Add a new poster
  addPoster: (options: CreatePosterOptions) => {
    const { posters, maxPosters } = get();

    // Check if max posters limit reached
    if (posters.length >= maxPosters) {
      console.warn(`Maximum number of posters (${maxPosters}) reached`);
      return null;
    }

    const id = generatePosterId();
    const now = Date.now();

    const newPoster: Poster = {
      id,
      imageUrl: options.imageUrl,
      position: options.position || DEFAULT_POSTER_POSITION,
      rotation: options.rotation || DEFAULT_POSTER_ROTATION,
      scale: options.scale || DEFAULT_POSTER_SCALE,
      createdAt: now,
      updatedAt: now,
    };

    set((state) => ({
      posters: [...state.posters, newPoster],
      selectedPosterId: id,
    }));

    return id;
  },

  // Remove a poster by ID
  removePoster: (id: string) => {
    set((state) => ({
      posters: state.posters.filter((poster) => poster.id !== id),
      selectedPosterId: state.selectedPosterId === id ? null : state.selectedPosterId,
    }));
  },

  // Update poster properties
  updatePoster: (id: string, updates: Partial<Poster>) => {
    set((state) => ({
      posters: state.posters.map((poster) =>
        poster.id === id ? { ...poster, ...updates, updatedAt: Date.now() } : poster,
      ),
    }));
  },

  // Select/deselect a poster
  selectPoster: (id: string | null) => {
    set({ selectedPosterId: id });
  },

  // Clear all posters
  clearPosters: () => {
    set({ posters: [], selectedPosterId: null });
  },

  // Get poster by ID
  getPosterById: (id: string) => {
    return get().posters.find((poster) => poster.id === id);
  },

  // Add uploaded poster
  addUploadedPoster: (poster: Omit<UploadedPoster, 'id' | 'uploadedAt'>) => {
    const id = generateUploadedPosterId();
    const uploadedPoster: UploadedPoster = {
      ...poster,
      id,
      uploadedAt: Date.now(),
    };

    set((state) => ({
      uploadedPosters: [...state.uploadedPosters, uploadedPoster],
      currentPosterImage: uploadedPoster.imageUrl,
    }));

    return id;
  },

  // Remove uploaded poster
  removeUploadedPoster: (id: string) => {
    set((state) => {
      const posterToRemove = state.uploadedPosters.find((p) => p.id === id);
      const newUploadedPosters = state.uploadedPosters.filter((p) => p.id !== id);

      // If the removed poster was the active selection, fall back to the
      // first remaining upload, or the bundled default when none are left.
      let newCurrentImage = state.currentPosterImage;
      if (posterToRemove && posterToRemove.imageUrl === state.currentPosterImage) {
        newCurrentImage =
          newUploadedPosters.length > 0 ? newUploadedPosters[0].imageUrl : DEFAULT_POSTER_IMAGE;
      }

      return {
        uploadedPosters: newUploadedPosters,
        currentPosterImage: newCurrentImage,
      };
    });
  },

  // Set current poster image
  setCurrentPosterImage: (imageUrl: string) => {
    set({ currentPosterImage: imageUrl });
  },

  // Merge server-persisted assets into the gallery without changing currentPosterImage
  hydrateUploads: (assets) => {
    set((state) => {
      const present = new Set(state.uploadedPosters.map((p) => p.id));
      const additions: UploadedPoster[] = assets
        .filter((a) => !present.has(a.id))
        .map((a) => ({
          id: a.id,
          imageUrl: a.url,
          name: a.originalName ?? 'Saved poster',
          uploadedAt: Date.now(),
          width: a.width,
          height: a.height,
        }));
      return additions.length
        ? { uploadedPosters: [...state.uploadedPosters, ...additions] }
        : state;
    });
  },
}));
