import type { FastifyInstance } from 'fastify';
import { z } from 'zod';
import type { MarkerBindingsRepo, MarkerBindingRow } from '../db/markerBindingsRepo.js';

/**
 * Upper bound on a stored asset URL. Generous enough for any S3/CloudFront
 * URL, small enough that a multi-megabyte `data:` URL cannot be smuggled into
 * a text column — poster BYTES belong in object storage via /api/assets, and
 * only the resulting URL belongs here.
 */
const MAX_ASSET_URL = 2048;

/**
 * Accepted asset URL forms: an absolute http(s) URL (a persisted asset), or a
 * site-root-relative path (a bundled asset such as /posters/default-poster.png).
 * Anything else — `data:`, `javascript:`, protocol-relative `//evil.example` —
 * is rejected, because this string is later fed to an <img>/texture loader.
 */
const assetUrl = z
  .string()
  .min(1)
  .max(MAX_ASSET_URL)
  .refine((v) => /^https?:\/\//i.test(v) || (v.startsWith('/') && !v.startsWith('//')), {
    message: 'assetUrl must be an http(s) URL or a site-relative path',
  });

/**
 * Marker names come from fingerprint JSON generated by the 8th Wall CLI. The
 * charset is restricted because the name is a URL path segment and a grouping
 * key; the length cap keeps it index-friendly.
 */
const MARKER_NAME_RE = /^[A-Za-z0-9 ._-]{1,128}$/;

/** A finite number — rejects NaN/Infinity, which would poison the transform. */
const finite = z.number().finite();

const localTransform = z.object({
  position: z.tuple([finite, finite, finite]),
  quaternion: z.tuple([finite, finite, finite, finite]),
  // A zero or negative scale would collapse or mirror the asset; a runaway
  // scale would fill the scene. Bound it to something physically plausible.
  scale: finite.positive().max(1000),
});

const bindingBody = z.object({
  assetUrl,
  assetName: z.string().max(256),
  local: localTransform,
});

const OWNER_ID_RE = /^[A-Za-z0-9_-]{1,64}$/;

/**
 * Extracts the per-device owner id. Identity, not authentication — the same
 * minimal model the asset routes use.
 *
 * @param req — The incoming request.
 * @returns The owner id, or null when the header is missing or malformed.
 */
function ownerOf(req: { headers: Record<string, unknown> }): string | null {
  const v = req.headers['x-owner-id'];
  return typeof v === 'string' && OWNER_ID_RE.test(v) ? v : null;
}

/**
 * Reshapes a database row into the nested wire format the client expects.
 *
 * @param r — A `marker_bindings` row.
 * @returns The binding with its transform re-nested under `local`.
 */
function toWire(r: MarkerBindingRow) {
  return {
    id: r.id,
    markerName: r.marker_name,
    assetUrl: r.asset_url,
    assetName: r.asset_name,
    local: {
      position: [Number(r.pos_x), Number(r.pos_y), Number(r.pos_z)],
      quaternion: [Number(r.quat_x), Number(r.quat_y), Number(r.quat_z), Number(r.quat_w)],
      scale: Number(r.scale),
    },
  };
}

/**
 * Registers the marker-space routes.
 *
 * `GET /api/spaces` returns a FLAT list of bindings rather than a nested
 * space-per-marker structure: the grouping is a client-side presentation
 * concern, and a flat list keeps the response shape stable if a binding ever
 * needs to reference more than one marker.
 *
 * @param app — The Fastify instance to register on.
 * @param deps — The bindings repository.
 */
export function registerSpaceRoutes(
  app: FastifyInstance,
  deps: { repo: MarkerBindingsRepo },
): void {
  const { repo } = deps;

  app.get('/api/spaces', async (req, reply) => {
    const owner = ownerOf(req);
    if (!owner) return reply.code(400).send({ error: 'missing x-owner-id' });
    const rows = await repo.listByOwner(owner);
    return reply.send({ bindings: rows.map(toWire) });
  });

  app.put('/api/spaces/:markerName/bindings/:id', async (req, reply) => {
    const owner = ownerOf(req);
    if (!owner) return reply.code(400).send({ error: 'missing x-owner-id' });

    const params = req.params as { markerName: string; id: string };
    if (!MARKER_NAME_RE.test(params.markerName)) {
      return reply.code(400).send({ error: 'invalid marker name' });
    }
    if (!z.string().uuid().safeParse(params.id).success) {
      return reply.code(400).send({ error: 'invalid binding id' });
    }

    const parsed = bindingBody.safeParse(req.body);
    if (!parsed.success) return reply.code(400).send({ error: 'invalid body' });
    const b = parsed.data;

    const ok = await repo.upsert({
      id: params.id,
      owner_id: owner,
      marker_name: params.markerName,
      asset_url: b.assetUrl,
      asset_name: b.assetName,
      pos_x: b.local.position[0],
      pos_y: b.local.position[1],
      pos_z: b.local.position[2],
      quat_x: b.local.quaternion[0],
      quat_y: b.local.quaternion[1],
      quat_z: b.local.quaternion[2],
      quat_w: b.local.quaternion[3],
      scale: b.local.scale,
    });
    if (!ok) return reply.code(409).send({ error: 'binding id belongs to another owner' });

    return reply.code(204).send();
  });

  app.delete('/api/spaces/:markerName/bindings/:id', async (req, reply) => {
    const owner = ownerOf(req);
    if (!owner) return reply.code(400).send({ error: 'missing x-owner-id' });
    const { id } = req.params as { id: string };
    if (!z.string().uuid().safeParse(id).success) {
      return reply.code(400).send({ error: 'invalid binding id' });
    }
    await repo.deleteById(id, owner);
    return reply.code(204).send();
  });
}
