/**
 * useUIState — global UI-state store (Zustand).
 *
 * Holds cross-component UI concerns that don't belong in posterStore: the
 * instructions overlay, the AR loading screen, and the transient toast queue
 * (auto-dismissed after `duration` ms). Despite the `use*` name it is a
 * store, not a React hook — call it anywhere.
 */

import { create } from 'zustand';
import { STORAGE_KEYS } from '@/utils/constants';

export interface ToastMessage {
  /** Unique ID assigned by the store; used to remove the toast later. */
  id: string;
  /** Visual style of the toast. */
  type: 'success' | 'error' | 'info';
  /** User-visible text. */
  message: string;
  /** Auto-dismiss delay in ms; defaults to DEFAULT_TOAST_DURATION_MS. */
  duration?: number;
}

/** How long a toast stays on screen when the caller doesn't say otherwise. */
const DEFAULT_TOAST_DURATION_MS = 3000;

interface UIState {
  // UI visibility states
  /** Whether the instructions/tutorial overlay is visible. */
  showInstructions: boolean;
  /** Whether the AR loading screen is visible. */
  showLoading: boolean;

  // Toast notifications
  /** Currently visible toasts, oldest first. */
  toasts: ToastMessage[];

  // Actions
  /**
   * Shows or hides the instructions overlay.
   *
   * @param show — New visibility. Passing false (dismissal) also persists
   *   "tutorial completed" to localStorage so the overlay is skipped on the
   *   next visit.
   */
  setShowInstructions: (show: boolean) => void;
  /**
   * Shows or hides the AR loading screen.
   *
   * @param show — New visibility; sets `showLoading` and nothing else.
   */
  setShowLoading: (show: boolean) => void;
  /**
   * Appends a toast to `toasts` and schedules its automatic removal.
   *
   * @param toast — Type, message, and optional `duration` in ms (defaults to
   *   DEFAULT_TOAST_DURATION_MS). The unique `id` is generated by the store.
   */
  addToast: (toast: Omit<ToastMessage, 'id'>) => void;
  /**
   * Removes a toast from `toasts` immediately (e.g. user tapped dismiss).
   *
   * @param id — ID of the toast to remove; unknown IDs are a no-op.
   */
  removeToast: (id: string) => void;
}

/**
 * Generates a unique toast ID.
 *
 * @returns A string like `toast-<timestamp>-<random>`, unique enough for a
 *   short-lived on-screen queue.
 */
const generateToastId = (): string => {
  return `toast-${Date.now()}-${Math.random().toString(36).slice(2, 11)}`;
};

/**
 * Writes to localStorage without ever throwing. iOS Safari in private
 * browsing (and some privacy configurations) rejects writes with a
 * "quota exceeded" error — the browser reports the storage area as full
 * even though nothing was stored. Tutorial persistence is a nice-to-have,
 * so degrade silently rather than crash the UI action.
 *
 * @param key — localStorage key to write.
 * @param value — String value to store.
 */
const safeStorageSet = (key: string, value: string): void => {
  try {
    localStorage.setItem(key, value);
  } catch {
    // Storage unavailable — the tutorial will simply show again next visit.
  }
};

/**
 * Reads from localStorage without ever throwing (see safeStorageSet for why
 * storage access can fail).
 *
 * @param key — localStorage key to read.
 * @returns The stored string, or null when the key is absent or storage is
 *   unavailable.
 */
const safeStorageGet = (key: string): string | null => {
  try {
    return localStorage.getItem(key);
  } catch {
    return null;
  }
};

/**
 * UI state store using Zustand.
 */
export const useUIState = create<UIState>((set, get) => ({
  // Initial state
  showInstructions: false,
  showLoading: false,
  toasts: [],

  // Set instructions visibility; dismissing marks the tutorial as completed.
  setShowInstructions: (show: boolean) => {
    set({ showInstructions: show });
    if (!show) {
      safeStorageSet(STORAGE_KEYS.TUTORIAL_COMPLETED, 'true');
    }
  },

  // Set loading state
  setShowLoading: (show: boolean) => {
    set({ showLoading: show });
  },

  // Add a toast notification and schedule its auto-dismissal.
  addToast: (toast: Omit<ToastMessage, 'id'>) => {
    const id = generateToastId();
    const newToast: ToastMessage = {
      id,
      type: toast.type,
      message: toast.message,
      duration: toast.duration || DEFAULT_TOAST_DURATION_MS,
    };

    set((state) => ({
      toasts: [...state.toasts, newToast],
    }));

    // Auto-remove toast after duration
    setTimeout(() => {
      get().removeToast(id);
    }, newToast.duration);
  },

  // Remove a toast by ID
  removeToast: (id: string) => {
    set((state) => ({
      toasts: state.toasts.filter((toast) => toast.id !== id),
    }));
  },
}));

/**
 * Reports whether the user has previously dismissed the instructions overlay.
 *
 * @returns True when the "tutorial completed" flag was persisted on an
 *   earlier visit; false otherwise (including when storage is unavailable).
 */
export const useTutorialCompleted = (): boolean => {
  return safeStorageGet(STORAGE_KEYS.TUTORIAL_COMPLETED) === 'true';
};
